- quickstart.mdx
Resolves #36.
Also added Windows instructions (I thought I had added these before, oops).
> Document `uv` as a prerequisite for the quickstart

- docs/first-server/python.mdx
requests.Session does blocking IO which blocks the event loop! No other requests can be processed concurrently
> use httpx.AsyncClient for async http requests

- docs/first-server/typescript.mdx
Servers shouldn't log to stdout, or they'll interfere with MCP communication happening there.
> Fix TypeScript first server logging to stdout

- docs/first-server/python.mdx
> docs: fix requests.HTTPError -> httpx.HTTPError

- docs/first-server/typescript.mdx
When running the weather typescript example with the code of the doc, Claude reports an error: `n.content.map is not a function` 
The error is due to the fact that the response to the tool request "get_forecast" is not compatible with the spec:
* content should be an array
* the mimeType is not supported as a text element, it should be type, and with the value text
Spec: https://spec.modelcontextprotocol.io/specification/server/tools/#tool-result
I checked the Python code and I see that the response is the same as the one that PR fixed:
```python
return [
TextContent(
type="text",
text=json.dumps(forecasts, indent=2)
)
]
```          
FWIW, I documented the process to fix that issue here: https://pcarion.com/blog/claude_mcp/
> update tool response in typescript weather sample to be compliant with spec

- docs/concepts/resources.mdx
https://github.com/modelcontextprotocol/docs/issues/45
Built and checked the preview. 
nope
doc change only
> Clarify that Claude Desktop does not automatically use resources

- docs/first-server/python.mdx
added async to the AsyncClient class that was missing, caused the test to fail with this error:
FAILED tests\weather_test.py::test_call_tool - TypeError: 'async with' received an object from __aenter__ that does not implement __await__: AsyncClient
Closes #64
> adding async to aenter in AsyncClient

- examples.mdx
All the paths to the reference implementations were incorrect, so I have fixed them.
> Fix broken links in examples.mdx file

- clients.mdx
Hi Anthropic! I'm excited to share I've just added MCP support to [Cline](https://github.com/cline/cline). Cline is a coding agent that can now respond to "add a tool that..." where he can extend his own capabilities by creating the necessary MCP server and configuring it in the extension, providing for a handsoff approach that I hope will make it easy for the community to contribute to your ecosystem. 
Here's a quick demo of MCP in Cline: https://x.com/sdrzn/status/1867271665086074969
Thank you for all your hard work in pushing MCP forward, I'm sure as we see wider adoption it will become more obvious to folks how much of a step change this is.
Cline added MCP support and this PR updates the clients page.
Tested with `mintlify dev` ✅
N/A
N/A
> Add Cline client

- clients.mdx
I'm adding [LibreChat](https://github.com/danny-avila/LibreChat) to the list of applications supporting the Model Context Protocol (MCP), highlighting its new integration capabilities.
- Reviewed documentation for technical correctness
- None. This is a documentation update only.
This update provides potential users and developers with insight into LibreChat's MCP support, emphasizing our commitment to open, extensible AI tooling.
> docs: Add LibreChat Client

- development/contributing.mdx
- development/roadmap.mdx
- introduction.mdx
- mint.json
Added a roadmap page (something frequently requested) which outlines our proposed H1 2025 priorities. I think this is mostly reflective of how we've been thinking about it, but please chime in if any of it seems wrong!
> Add Development section with Contributing and Roadmap pages

- docs/concepts/roots.mdx
- mint.json
- Update roots.mdx to clarify that roots are not limited to filesystem paths
- Add examples of HTTP URIs as roots
- Clarify that roots are informational/suggestive rather than enforcing
- Review documentation changes for accuracy and clarity
> Update roots.mdx to clarify that roots can be any URI

- docs/tools/debugging.mdx
- Add documentation about working directory behavior for MCP servers
- Clarify that working directory is undefined when launched via Claude Desktop
- Add guidance to use absolute paths in configuration files
- Verify documentation is clear and accurate
- Check that example configuration uses absolute paths
- Ensure guidance helps users avoid working directory issues
> Simplify logging comment in TypeScript first server guide

- quickstart/server.mdx
Use quotes to avoid shell interpretation; i.e. `uv add "mcp[cli]"` instead of `uv add mcp[cli]`
The document says to run `uv add mcp[cli]` but it causes an error on Mac/Linux due to the shell interpretation of `[]`
This is a one-line PR to fix the issue and allow the reader to simply cut and paste the command.
The updated file has been verified with `mintlify dev`
N/A
Thanks for taking care of this!
> quickstart: Use quotes to avoid shell interpretation for `uv add mcp[cli]`

- quickstart/server.mdx
- Add missing server initialization instructions to Python quickstart guide
- Clean up formatting and whitespace in server.mdx
> docs: add server initialization instructions to quickstart guide

- quickstart/user.mdx
Fixing trailing `` ` `` breaks MacOS/Linux cli example for "https://modelcontextprotocol.io/quickstart/user#server-not-showing-up-in-claude-hammer-icon-missing" in issue [#105](https://github.com/modelcontextprotocol/docs/issues/105)
Although it's a minor issue, may confuse more novice users
1. Running `mintlify dev`
2. Navigating to the section [https://modelcontextprotocol.io/quickstart/user#server-not-showing-up-in-claude-hammer-icon-missing](https://modelcontextprotocol.io/quickstart/user#server-not-showing-up-in-claude-hammer-icon-missing)
3. copying the code for the `MacOS/Linux` tab
4. pasting the command in the terminal and pressing `Enter`
none
Before the change, running the code sample displayed:
```
) npx -y @modelcontextprotocol/server-filesystem /Users/username/Desktop …
```
> fix: trailing '`' breaks MacOS/Linux cli example for "quickstart/user#server-not-showing-up-in-claude-hammer-icon-missing"

- quickstart/user.mdx
Added a Warning box to the User QuickStart guide to remind people to only add trusted commands.
To remind users to verify commands added to the Configuration File as by design Claude Desktop will execute arbitrary commands at the current privilege level. 
Other mentions of "security" in this guide tend to reinforce that the MCP is secure potentially giving false reassurance.
Using mintlify as per the contributing guidelines.
No.
> Added a Warning to "User Quickstart" to remind the User to only add trusted commands

- quickstart/server.mdx
Added warning to help with https://github.com/modelcontextprotocol/docs/issues/96
People are hitting issues with paths, this should give people some breadcrumbs to follow to fix issues in the quickstart
Tested locally 
N/A
> Added warning regarding the uv command in the quickstart guide

- docs/concepts/transports.mdx
I was working through implementing an SSE server in TypeScript, and this is the current example:
```typescript
const server = new Server({
name: "example-server",
version: "1.0.0"
}, {
capabilities: {}
});
const transport = new SSEServerTransport("/message", response);
await server.connect(transport);
```
It is unclear what `response` is meant to be here, and this seems to be just the definition for the `GET` part of the connection (there no mention of `transport.handlePostMessage`).
The example I've created has close parity with the equivalent Python example (using `express` as an analog to `Starlette`).
I tested the code while working on my server [here](https://github.com/tadasant/mcp-server-stability-ai/blob/6c906e28f43527cdb563bcf4f57c524b8b4dbc37/src/sse.ts) by connecting to it with …
> Fix example for implementing SSE Server in TypeScript

- docs/tools/debugging.mdx
A stock install of Claude Desktop doesn't seem to have a `developer_settings.json` file, so the setup instructions for Chrome Dev Tools on the Debugging are incomplete.
This adjusts
See above. Note this does not fix the unspoken dependency on `jq`, and like a lot of things in the docs, is currently Mac-specific
I'm on a Mac with jq. I've tested it with the file missing, the file present w/ my own changes, and the file present but empty
Nothing
Love MCP so far, keep up the great work, will keep the docs PRs coming if welcome :)
> Debugging page: adjust one-liner to create developer_settings.json file if necessary

- docs/concepts/architecture.mdx
- docs/concepts/prompts.mdx
- docs/concepts/resources.mdx
- docs/concepts/tools.mdx
- quickstart/server.mdx
This updates the docs to use the simplified, Express-like TypeScript API [released](https://github.com/modelcontextprotocol/typescript-sdk/releases) in SDK version 1.3.0.
> Update TypeScript examples to use simplified API

- quickstart/user.mdx
Some Windows users may not be able to easily configure and use MCP Servers. This appears to impact largely (if not exclusively) those users who installed Node via the official MSI installer. These users tend to report seeing `ENOENT` errors in their logs, as well as a literal instance of `${APPDATA}`  in the associated path.
**Note:** This PR is a proposal; I'm certain that the explanation and presentation can be improved upon. I submit this PR with the hopes that somebody else, with a fresh set of eyes, will evaluate the issue and contribute additional insight.
After some investigation, I found that this problem arises when _npx_ determines where to install files, specifically when it attempts to construct the desired _prefix_. During this process Node loads `C:\Program …
> Explains cause/solution for ${APPDATA} ENOENT

- clients.mdx
Added an entry for [mcp-agent](https://github.com/lastmile-ai/mcp-agent) to the MCP client docs.
`mcp-agent` is a framework that makes it easier to build agent workflows using MCP servers. It is worthwhile for the community to have it as an option when building MCP apps.
The framework is thoroughly tested. Please see examples here: https://github.com/lastmile-ai/mcp-agent/tree/main/examples
No breaking changes
> Add mcp-agent to list of clients

- docs.json
The Java SDK anchor is missing from the navigation menu
> Add missing Java SDK anchor

- clients.mdx
- Simplify and improve description
- Fix formatting and alignment in the table
- Update link reference from [codeium] to [Windsurf]
- Maintain consistent style with other entries
This change improves the documentation quality and consistency by:
- Making the Windsurf Editor description more concise and professional
- Ensuring consistent formatting across all client entries
- Using consistent naming and reference conventions
- Aligning with the documentation style of other MCP clients
- Verified markdown rendering locally
- Checked table alignment and formatting
- Confirmed all links are working correctly
- Ensured consistent spacing and indentation
No breaking changes. This is a documentation-only update that improves readability and consistency.
- [✓] Documentation update
- [✓] I have …
> feat: add windsurf in clients

- quickstart/user.mdx
I occasionally came across this typo and wanted to fix it.
Tested by running `mintlify dev` and checking the output.
> fix: correct typo in quickstart/user.mdx

- clients.mdx
Hi! I'm excited to share I've just added MCP support to [OpenSumi](https://github.com/opensumi/core). OpenSumi is a framework that helps you quickly build AI-native IDE products. It now supports MCP Client functionalities. With this, OpenSumi can support other third-party MCP Servers.
OpenSumi added MCP support and this PR updates the clients and servers page.
YES
N/A
ScreenShots of OpenSumi MCP features: 
https://github.com/opensumi/core/blob/main/packages/ai-native/MCP.md
> Add OpenSumi to client and server list

- quickstart/client.mdx
- quickstart/server.mdx
This PR relies on the `quickstart-resources` [PR](https://github.com/modelcontextprotocol/quickstart-resources/pull/10) merging first as it links to the Python and Typescript MCP clients.
Specifically, this change will add a section to the Quickstart For Client Developers focused on Node/Typescript
MCP Client tutorials exist for Python and Java but not Node. Including this section improves the DX for MCP Client developers.
The code in this tutorial was validated via connecting to multiple MCP Servers locally.
None
Fixes https://github.com/modelcontextprotocol/docs/issues/103
> Add Tutorial for Creating an MCP Client in Typescript

- quickstart/client.mdx
- quickstart/server.mdx
The link to "Building MCP with LLMs" in `client.mdx` and `server.mdx` is broken. Fixing it to point to the correct path `/tutorials/building-mcp-with-llms`
Fixes a broken link
> Fix broken link in client.mdx and server.mdx

- quickstart/client.mdx
The client program will work even if the variable `tool_results` is removed
I wrote a client in Python according to the quickstart and executed it to work.
https://gist.github.com/ftnext/9988e2f9929f836557091012b4160061
> [docs(client quickstart)] Remove unused variable

- clients.mdx
Adding SpinAI.dev, an open source typescript ai agent framework that now natively supports MCP to the clients list.
There's been a lot of demand to allow our AI agents to natively use MCP agents, so we added it:
https://docs.spinai.dev/mcp/overview :) Great work guys!
> Add SpinAI.dev to list of clients

- clients.mdx
> feat: adds Daydreams agents

- sdk/java/mcp-server.mdx
The documentation for the Java SDK was a little bit out of sync and led to few hurdles when trying to set up things quickly.
This PR changes the following things:
- Add an example for a JSON schema to the `Tool` class.
> Fix Java SDK documentation where it's incosistent to API

- quickstart/client.mdx
The code example use `readline`
```ts
......
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import readline from "readline/promises";
import dotenv from "dotenv";
```
Based on [NodeJS official document](https://nodejs.org/api/readline.html#class-readlinepromisesinterface)
`readline` requires NodeJS 17 or above
Update document
Update document only
No
> doc: update file `quickstart/client.mdx` with correct NodeJS version

- quickstart/client.mdx
The current python quick start client docs point to the incorrect folder and file.  The sample project has since changed and the new folder structure of the mcp server for weather.py should be reflected in the run command in the docs.
Ran this command with the correct path from the cloned quick-start repo.
The new path in the mcp server weather sample is: ../quickstart-resources/weather-server-python/weather.py
No.
- [ x] Documentation update
> Update the python client quickstart docs uv run path

- clients.mdx
Add fast-agent to the MCP Clients list
> add fast-agent to clients list

- quickstart/client.mdx
- quickstart/server.mdx
Update Spring AI dependency artifact IDs in documentation to follow the new naming convention:
- spring-ai-mcp-client-spring-boot-starter → spring-ai-starter-mcp-client
- spring-ai-anthropic-spring-boot-starter → spring-ai-starter-model-anthropic
- spring-ai-mcp-server-spring-boot-starter → spring-ai-starter-mcp-server
This is to align the quickstart documentation with the changes to be released with Spring-AI 1.0.0-M7
> refactor: update Spring AI artifact IDs to new naming convention

- development/updates.mdx
Kotlin-sdk 0.4.0 has been released with bug fixes and improvements.
> Add Kotlin-sdk 0.4.0 to updates

- quickstart/server.mdx
Aa a kotlin developer it was strange to read. 
This is how it looks right know:
Haven't tested it 🤷‍♂️ 
Nope
> Fix kotlin defaultRequest indention

- clients.mdx
Copilot Studio recently added MCP support - starting with Tools. 
[Release announcement](https://www.microsoft.com/en-us/microsoft-copilot/blog/copilot-studio/introducing-model-context-protocol-mcp-in-copilot-studio-simplified-integration-with-ai-apps-and-agents/ )
Yes
No
> Add Copilot Studio to client examples

- clients.mdx
This is the updated official name of the library (no brand prefix).
> Update name of Genkit

- quickstart/client.mdx
- quickstart/server.mdx
Received some feedback from the .NET samples, so incorporated that
> Updating to align with quickstart sample

- sdk/java/mcp-client.mdx
- sdk/java/mcp-overview.mdx
- sdk/java/mcp-server.mdx
- Emphasize that core mcp module includes default STDIO and SSE transport implementations
- Clarify that default implementations don't require external web frameworks
- Mark Spring-specific transport implementations as optional dependencies
> docs(java): clarify core vs optional transport implementations

- docs/concepts/architecture.mdx
`asyncio.run` expects a coroutine, not a function.
Running the example errors with:
```
asyncio.run(main)
~~~~~~~~~~~^^^^^^
File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
return runner.run(main)
~~~~~~~~~~^^^^^^
File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 89, in run
raise ValueError("a coroutine was expected, got {!r}".format(coro))
ValueError: a coroutine was expected, got <function main at 0x105a8fce0>
```
Ran the fix.
No
n/a
> Fix `python` snippet in `Core architecture`

- clients.mdx
👋 from the VS Code team.
Introduce support for VS Code GitHub Copilot. We didn't just add tools, but also `roots` and list_changed events for dynamic tool discovery.
Check out the one-click install on https://github.com/github/github-mcp-server/ or via `MCP: Add Server`.
Supersedes https://github.com/modelcontextprotocol/docs/pull/270 as I added a few more actual features, less marketing buzz.
> Add VS Code GitHub Copilot integration
