modelcontextprotocol/docs

docs/first-server/typescript.mdx

Update typescript documentation to warn users not to include their sensitive data in git

Update documentation to include hiding .env

---

docs/first-server/typescript.mdx

Based on https://github.com/modelcontextprotocol/typescript-sdk/issues/72.

Simplify/clarify TS first server `command`

---

docs/first-server/typescript.mdx

Updates the log dir on MacOS in the TS quickstart
The quick start lists a command to tail logs, but it seems to be pointing at the wrong place
👀
no

update log dir

---

docs/first-server/python.mdx

see 
https://github.com/modelcontextprotocol/python-sdk/pull/77

Fix docs on resource template usage

---

clients.mdx

Firebase Genkit support has been added, so adding it to the list of supported clients.

Adds Firebase Genkit to client list

---

CONTRIBUTING.md
mint.json

- Added a "thumbs up/down" feedback feature to our mint.json

Adding thumbs up/down feedback to our docs

---

clients.mdx

Adds Continue (https://continue.dev) to the clients page
Continue recently added support for MCP. This updates the clients page to reflect that
Tested the docs with `mintlify dev`
N/A

Add Continue client

---

clients.mdx

Listing GenAIScript as potential client
Updating the list of known clients
Running `mintlify dev` locally
No

adding genaiscript client

---

quickstart.mdx
tutorials/building-a-client.mdx

Better troubleshooting guidance

---

mint.json

add kotlin sdk to mintlify docs

add kotlin sdk

---

clients.mdx

fixed #89
Added Theia AI and Theia IDE as MCP clients.
The tools support MCP.

Add Theia AI and Theia IDE as a client

---

tutorials/building-a-client-node.mdx

Update the node MCP client sample code to run with the latest anthropic-ai/sdk 0.33 release.
I followed the instructions in [tutorials/building-a-client-node.mdx](https://github.com/modelcontextprotocol/docs/blob/main/tutorials/building-a-client-node.mdx) and found that it doesn't work as is.
I had to make the following two changes:
- Removal of the reference to `Tool` type. 
As of 0.33.x (now the latest version), anthropic-ai/sdk no longer contains `resources/messages` where `Tool` used to be declared.
Its only use was in `const availableTools: Tool[] = toolsResponse.tools.map(...`.
Removing the type annotation `: Tool[]` from there seems to be fine as the code seems to create the same structure that the Anthropic API expects. 
Please let me know if you would rather me import `Tool` from …

Update the node client example for anthropic-ai/sdk 0.33

---

examples.mdx

Adds [Supergateway](https://github.com/supercorp-ai/supergateway) to Additional resources. It is a tool that allows running stdio transport MCP servers over SSE transport.
Now most community MCP servers only support stdio transport and this is problematic if you want remote assistants to access them. MCP spec has SSE transport which works with remote HTTP connections but it is rarely used by MCP server authors. This gateway allows you to run stdio transport MCP servers wrapping them in SSE transport.
Running in production for Superinterface customers.
None.

Add Supergateway to Additional resources

---

clients.mdx

5ire is an open-source, cross-platform desktop AI assistant that is compatible with mainstream LLM service providers. It supports local knowledge bases and custom prompt libraries, offering a simple and friendly interactive experience. Now, it supports tools through MCP servers.
Because we're excited to announce that there's a new MCP client available.
Yes, through unit testing and manual testing on both Mac and Windows systems.
None.
Support for MCP Servers is still in its early stages, our roadmap includes expanded support for MCP features in the future.

Add 5ire to MCP client list

---

quickstart/server.mdx

- Updates Python quickstart documentation to use the new FastMCP API
- Simplifies code examples and improves error handling
- Makes the documentation more consistent with the current SDK version

docs: Update Python quickstart to use FastMCP API

---

clients.mdx

Adds [Bee Agent Framework](https://i-am-bee.github.io/bee-agent-framework/#/) to the list of clients

Reference Bee Agent Framework in client examples

---

docs/concepts/architecture.mdx
docs/concepts/prompts.mdx
docs/concepts/resources.mdx
docs/concepts/tools.mdx
quickstart/server.mdx

Nope, these changes were busted…
Reverts modelcontextprotocol/docs#115.

Revert "Update TypeScript examples to use simplified API"

---

quickstart/server.mdx

https://github.com/modelcontextprotocol/docs/pull/115 redux, incorporating the new quickstart code from https://github.com/modelcontextprotocol/quickstart-resources/pull/7.

Update Node quickstart to use simplified API

---

introduction.mdx

Added MCP support email to the introduction.mdx

Added MCP support email

---

clients.mdx

fix #128 
The tools support MCP

Add Emacs mcp to the list of supportint clients

---

examples.mdx

Adds Stripe's MCP server to the Official integrations list
Docs update
N/A

add Stripe to Official integrations list

---

quickstart/client.mdx
quickstart/server.mdx
sdk/java/mcp-client.mdx
sdk/java/mcp-overview.mdx

- Fix typos and update links in quickstart guides
- Update artifact names and configuration properties
- Add detailed configuration examples and advanced features
- Enhance Java SDK client/server documentation
- Update architecture diagrams and descriptions
- Improve code examples with better comments
- Update Spring Boot version requirements

docs: improve Java SDK documentation and examples

---

clients.mdx

Documentation update: "Bee Agent Framework" rebranded to "BeeAI Framework" and the URLs changed.
By clicking the new URLs.
No.

Update Bee Agent Framework -> BeeAI Framework

---

docs/concepts/architecture.mdx

fixed mermaid diagram in /architecture 

---

clients.mdx

Fix of OpenSumi MCP Client page display error.
Sorry for my carelessness @dsp-ant

fix: OpenSumi MCP Client Document format error

---

docs/concepts/architecture.mdx

Within the graph, just added a space so the title can be visible.
The title wasn't being shown entirely and the example shown in the graph was the same described in the text above. The example was causing the title to not be visible and was just adding a redundant info.
Using mintlify, just checked visualy.
n/a

docs: Update architecture diagram host label

---

quickstart/client.mdx
quickstart/server.mdx

fix: package.json by remove trailing comma

---

clients.mdx

Added oterm a terminal UI client for Ollama that supports MCP tools.
Generated docs fine.
None.

Add oterm (https://github.com/ggozad/oterm as a tool-supporting client.

---

development/roadmap.mdx

Change ~enabling~ to _improving_ and link to [this discussion](https://github.com/modelcontextprotocol/specification/discussions/112) instead of [this discussion](https://github.com/modelcontextprotocol/specification/discussions/102).
I've seen this roadmap get misquoted at least twice in the last couple days, in addition to [this issue](https://github.com/modelcontextprotocol/specification/issues/168#issuecomment-2668914972) being opened. I think it's because there is a growing amount of more mainstream attention on MCP, and so people are hunting for answers as why they need to use tools like `npx` to run stdio servers. Then they see this in the roadmap:
> Our top priority is enabling [remote MCP connections](https://github.com/modelcontextprotocol/specification/discussions/102), …

fix: clarify language on roadmap regarding "enabling remote connections"

---

introduction.mdx

Mahesh from Anthropic recently did a 2hr workshop on MCP which could serve as a good introduction for all to see.
n/a
none

add Anthropic workshop to introduction

---

examples.mdx

Hi!
I've added the MCP Weaviate server to the documentation under `Example Servers`. 
N/A docs change
None

Add Weaviate Server to the Examples List

---

quickstart/client.mdx

Added a Kotlin tab to the quickstart client guide
tested locally
No breaking changes

Add Kotlin client quickstart

---

quickstart/server.mdx

Removed unnecessary parenthesised statement

---

quickstart/server.mdx

Added a Kotlin tab to the quickstart server guide
These updates provide a clear, step-by-step guide for Kotlin developers
tested locally
No breaking changes

Add Kotlin server implementation guide for weather server to quickstart

---

quickstart/client.mdx
quickstart/server.mdx

Update version to 0.4.0
Remove `onCloseCallback` in server guide
No breaking changes

update mcp kotlin-sdk version to 0.4.0 in quickstart

---

quickstart/server.mdx

simplify creating input schema for kotlin server in quickstart

---

quickstart/server.mdx

Mismatched parenthesis in Java code example
fixed parenthesis mismatch in java code example
Code example doesn't compile
Compiled in local IDE
no
- [] New and existing tests pass locally
- [] I have added appropriate error handling

fixed parenthesis mismatch in Java code example
